services:
  ros2_jammy_sim:
    build:
      context: ./
      dockerfile: ./DockerFiles/Dockerfile
      args:
        - BASE_IMAGE=osrf/ros
        - BASE_TAG=jazzy-desktop-full
        - DISTRO=jazzy
        - WORKSPACE=docker_simulation_ws
        - USERNAME=ros
        - USER_UID=1000
        - USER_GID=1000

    container_name: ros2_jammy_simulator
    networks:
      - ros2_internal

    stdin_open: true
    tty: true

    # wichtig für Gazebo/Qt/Rendering
    shm_size: "2gb"

    environment:
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - GZ_VERSION=harmonic

      # NVIDIA Container Runtime
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all

      # VNC Settings
      - DISPLAY=:1
      - VNC_GEOMETRY=1920x1080
      - VNC_DEPTH=24
      - VNC_PASSWORD=change-me

    ports:
      - "5901:5901"   # VNC (TurboVNC)

    volumes:
      - ~/.bash_history:/home/ros/.bash_history
      - ./docker_simulator:/home/ros/docker_simulation_ws

    # kein privileged nötig, kein /dev/nvidia* Mount nötig, kein /tmp/.X11-unix Mount nötig
    runtime: nvidia

networks:
  ros2_internal:
    driver: bridge
